"""Initial migration

Revision ID: 5d2038d88554
Revises: 
Create Date: 2025-11-12 18:51:38.910103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d2038d88554'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_categories', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
